-- RIADH CARD — Customer ratings and feedback
-- Apply after 004_merchant_profile_settings.sql.

CREATE EXTENSION IF NOT EXISTS pgcrypto;

CREATE TABLE IF NOT EXISTS public.merchant_reviews (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  merchant_id uuid NOT NULL REFERENCES public.merchants(id) ON DELETE CASCADE,
  customer_id uuid NOT NULL REFERENCES public.customers(id) ON DELETE CASCADE,
  rating smallint NOT NULL CHECK (rating BETWEEN 1 AND 5),
  comment text CHECK (char_length(comment) <= 500),
  -- Automatically generated by the API, e.g. "Amine B.". Never store the full display name here.
  display_name text NOT NULL CHECK (char_length(display_name) BETWEEN 1 AND 40),
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT merchant_reviews_one_per_customer UNIQUE (merchant_id, customer_id)
);

CREATE INDEX IF NOT EXISTS merchant_reviews_merchant_updated_idx
  ON public.merchant_reviews (merchant_id, updated_at DESC);

ALTER TABLE public.merchant_reviews ENABLE ROW LEVEL SECURITY;

-- Direct table reads stay blocked: the public PWA reads through /api/reviews,
-- which removes customer_id before returning any review.
DROP POLICY IF EXISTS "Public can read merchant reviews" ON public.merchant_reviews;

-- Writes use the authenticated server route, which verifies the customer has a loyalty card.
-- It then uses the service role to upsert exactly one review per customer and merchant.
